settings:
  table_width: 91
  table_title: "Game time statistics"
  polling_timeout: 1 # In seconds

applications:
  # Each application MUST have a name and a process name
  # - name: Application
  # - process: application.exe
  - name: Notepad
    process: notepad.exe
  - name: Notepad ++
    process: notepad++.exe